initial test with tomcat and springboot

diff --git a/mainsite/Jenkinsfile b/mainsite/Jenkinsfile
--- a/mainsite/Jenkinsfile
+++ b/mainsite/Jenkinsfile
@@ -1,16 +1,43 @@
 pipeline {
   agent any
 
+  tools {
+    maven 'Maven 3.8.5'
+  }
+
+  environment {
+    IMAGE_NAME = "TylerPacDevelopment/mainsite"
+  }
+
   stages {
-    stage('Start Shared MySQL DB') {
+    stage('Build WAR') {
       steps {
-        sh 'docker compose up -d mysql'
+        dir('mainsite') {
+          sh 'mvn clean package'
+        }
+      }
+    }
+
+    stage('Build Docker Image') {
+      steps {
+        dir('mainsite') {
+          sh "docker build -t ${IMAGE_NAME}:latest ."
+        }
+      }
+    }
+
+    stage('Deploy Container') {
+      steps {
+        sh "docker stop ${IMAGE_NAME} || true"
+        sh "docker rm ${IMAGE_NAME} || true"
+        sh "docker run -d --name ${IMAGE_NAME} -p 8080:8080 --network=backend ${IMAGE_NAME}:latest"
       }
     }
   }
+
   post {
-      success {
-          echo "✅ MySQL container is running."
+    success {
+          echo "✅ mainsite deployed."
           httpRequest httpMode: 'POST',
                       contentType: 'APPLICATION_JSON',
                       requestBody: """{
@@ -23,7 +50,7 @@ pipeline {
                       url: 'https://n8n.tylerpac.dev/webhook/TylerPacDevelopment'
       }
       failure {
-          echo "❌ Failed to bring up MySQL."
+          echo "❌ mainsite Failed to deploy."
           httpRequest httpMode: 'POST',
                       contentType: 'APPLICATION_JSON',
                       requestBody: """{
